#ifndef DSP_CONST_STAR_GEN_H
#define DSP_CONST_STAR_GEN_H

#define DSP_MAX_STARS 64
#define DSP_MAX_TEMP_POSES 256
#define DSP_MAX_DRUNK 8

#define POSES_ITER_COUNT 4
#define POSES_MIN_DIST 2.0
#define POSES_MIN_STEP_LEN 2.3
#define POSES_MAX_STEP_LEN 3.5
#define POSES_FLATTEN 0.18
#define POSES_MIN_DRUNK_NUM 6
#define POSES_MAX_DRUNK_NUM 8
#define POSES_ATTEMPTS 256
#define POSES_WALK_ROUNDS 256
#define POSES_WALK_PROB 0.7
#define POSES_MIN_D_SQ 1e-8

#define BLACK_HOLE_BASE 0.01
#define BLACK_HOLE_RAND 0.3
#define NEUTRON_STAR_BASE 0.01
#define NEUTRON_STAR_RAND 0.3
#define WHITE_DWARF_BASE 0.016
#define WHITE_DWARF_RAND 0.4
#define GIANT_STAR_BASE 0.013
#define GIANT_STAR_RAND 1.4

#define FORCED_M_INDEX 3

#define SPECTR_FACTOR_M (-3.0f)
#define SPECTR_FACTOR_O 4.65f

#endif
